задача 1

In [33]:
import numpy as np
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


задача 2

In [34]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(np.diag(a,1))

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


задача 3

In [35]:
import numpy as np
a = np.arange(25)
a[(a >= 3) & (a <= 8)] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


задача 4

In [36]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, obj=[1, 2, 3, 4], values = 0)
c = np.insert(b, obj=[2, 4, 6, 8], values = 0)
d = np.insert(c, obj=[3, 6, 9, 12], values = 0)
print(d)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


задача 5

In [37]:
import numpy
a = np.array([[1,2,3], [0,0,0], [9,3,5]])
a[[0,2]] = a[[2, 0]]
print(a)

[[9 3 5]
 [0 0 0]
 [1 2 3]]
