Задача 1.

Создать матрицу размером 10х10 с 0 внутри, и 1 на границах. Например для 3х3.

In [5]:
import numpy as np
matrix = np.ones((10,10), int)
matrix[1:9,1:9] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]




Задача 2.

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

Количество строк кода идеального решения: 1
Кроме print()


In [3]:
import numpy as np
print(np.diag(np.arange(1, 5), k=1))

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]




Задача 3.

Дан массив, поменять знак у элементов, значения которых между 3 и 8.


In [4]:
import numpy as np
matrix = np.full((10, 10), 5)
matrix[(matrix > 3) & (matrix < 8)] *= -1
print(matrix)

[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]]


Задача 5.

Дана матрица MxN. Поменять 2 любые строки в матрице

In [7]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], int)
pudge = matrix[1].copy()
matrix[1] = matrix[2]
matrix[2] = pudge
print(matrix)

[[1 2 3]
 [7 8 9]
 [4 5 6]]




Задача 7.

Дан массив 16x16, посчитать сумму по блокам 4x4.


In [6]:
import numpy as np
matrix = np.ones((16,16), int)
pudge = matrix.reshape(4, 4, 4, 4).sum(axis=(2,3))
print(pudge)

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
