In [2]:
#1
import numpy as np

m = np.ones((10,10))

m[1:-1, 1:-1] = 0
print (m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
#2
import numpy as np

m = np.diag([1,2,3,4],k = 1)
print(m)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [6]:
#3
import numpy as np
a = np.array([[1, 2, 3, 4]], int)
l = np.logical_and(a > 3, a < 8)
a[l] = -a[l]
print(a)

[[ 1  2  3 -4]]


In [14]:
#6
import numpy as np
m = np.array([6,7,9,1,2,2])
print(np.bincount(m).argmax())


2


In [12]:
#7
import numpy as np
matrix = np.ones((16,16))
for i in range(0, 16,4):
        print(np.sum(matrix[i:i+4,j:j+4]))

16.0
16.0
16.0
16.0
