№1

In [6]:
import numpy as np
k = np.ones((10, 10))
k[1:-1, 1:-1] = 0
k

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

№2

In [20]:
x = np.zeros((5, 5))
np.diag(np.arange(1, 5), 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

№3

In [29]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], int)
x[np.logical_and(x >= 3, x <= 8)] *= -1
x

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

№4

In [59]:
x = np.zeros((5, 4))
a = np.array([1, 2, 3, 4, 5])
x[:, 0] = a
x = x.reshape(1, 20)[0, :17]
x

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])