In [1]:
[1]
import numpy as np
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
[2]
import numpy as np
diagonal = np.arange(1, 5)
matrix = np.diag(diagonal, 1)
print(matrix)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [3]:
[3]
a = np.array([1, 6, 8, 5, 8, 4, 8])
mask = (a > 3) & (a < 8)
a[mask] = -a[mask]
print(a)


[ 1 -6  8 -5  8 -4  8]


In [4]:
[6]

a = np.array([1, 2, 2, 2, 3, 3, 3, 3, 3])
maxx = np.bincount(a)
val = np.argmax(maxx)
print(val)


3


In [ ]:
1 3 5

In [5]:
[12]

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
maxx = 0
for i in range (len(x) - 1):
    if x[i] == 0 and maxx < x[i + 1]:
        maxx = x[i + 1]
print(maxx)


5
