Задача 1.

In [ ]:
import numpy as np

s = np.ones((10, 10), int)
s[1:9, 1:9] = 0
print(s)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Задача 2.

In [ ]:
import numpy as np

print(np.diag(np.arange(1, 5), k=1))


[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


Задача 3.

In [6]:
import numpy as np

s = np.arange(10)
s[(s > 2) & (s < 9)] *= -1
print(s)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


Задача 5.

In [10]:
import numpy as np

s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
s[1] = np.array([0, 0, 0])
print(s)

[[1 2 3]
 [0 0 0]
 [7 8 9]]
