1 задача


In [ ]:

import numpy as np
a=np.ones((10,10))
a[1:9, 1:9]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2 задача

In [ ]:
import numpy as np
a = np.arange(1, 5)
b = np.diag(a, 0)
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


3 задача

я не очень понимаю как ввести просто массив, без заранее известного количества элементов массива, поэтому тут просто рандомные цифры


In [ ]:
a = ([1, 9, 10, 6, 12, 5, 4.4 ])
for i in range(len(a)):
  if a[i]>3 and a[i]<8:
    a[i]=-a[i]
print(a)


[1, 9, 10, -6, 12, -5, -4.4]


задача 6


In [ ]:
import numpy as np
a = np.array([1, 44, 55, 44, 44, 44, 39, 55, 1, 2, 2])
x = np.bincount(a)
z = np.argmax(x)
print(z)


44


задача 4

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) * 4 - 3)

b[::4] = a

print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


задача 5

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [0, 0, 0], [9, 3, 5]])
a[0], a[2] = a[2], a[0].copy()

print(a)


[[9 3 5]
 [0 0 0]
 [1 2 3]]


задача 8

In [ ]:
import numpy as np

a = np.random.rand(100, 10000)
n = int(input())
a = np.sort(a.flatten())[-n:]
print(a)

123
[0.99985494 0.99985743 0.99985761 0.99985844 0.99985848 0.9998587
 0.99985955 0.99986015 0.99986376 0.99986664 0.99986698 0.99986705
 0.99986741 0.99986763 0.99986862 0.99986864 0.99986887 0.99986965
 0.99986978 0.99986989 0.99987177 0.99987214 0.99987303 0.99987425
 0.99987469 0.9998758  0.99987688 0.99987743 0.99987763 0.99987789
 0.99987855 0.99988067 0.99988297 0.99988492 0.999885   0.99988541
 0.99988635 0.999887   0.9998886  0.9998888  0.9998892  0.99989195
 0.99989334 0.99989351 0.99989575 0.99989937 0.99990097 0.99990135
 0.99990162 0.99990251 0.99990346 0.99990479 0.99990776 0.99990872
 0.99990961 0.99991049 0.9999125  0.99991401 0.99991627 0.99991638
 0.99991673 0.99991706 0.99991712 0.99991774 0.99991937 0.99992104
 0.99992538 0.99992644 0.99992705 0.99992799 0.99993206 0.99993294
 0.9999338  0.99993387 0.99993439 0.99993524 0.99993647 0.99993685
 0.99993775 0.99993809 0.99993907 0.9999408  0.9999415  0.99994278
 0.99994279 0.99994402 0.99994411 0.999945   0.99994912 0.9

задача 10

In [ ]:
import numpy as np

A = np.array([8.9, -5.5, 0.25, -1.12, 3.0, -22.5, -14.9])
Z = np.where(A > 0, np.ceil(A), np.floor(A))
print(Z)

[  9.  -6.   1.  -2.   3. -23. -15.]


задача 11


In [ ]:
import numpy as np

A = np.array([5, 12, 34, 55, 90])
B = np.array([5, 8, 34, 12, 7])
Z = np.intersect1d(A, B)
print(Z)


[ 5 12 34]


задача 12


In [ ]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a = 0
for i in range (len(x) - 1):
    if x[i] == 0 and a < x[i + 1]:
        a = x[i + 1]
print(a)

5


задача 13

In [ ]:
import numpy as np

a = np.random.random((9, 3))
x = np.linalg.norm(a, axis=1)
y = np.argmax(x)
z = a[y]
maxdlina = vector_lengths[y]
print("Исходное:")
print(a)
print("\nДлины векторов:")
print(x)
print("\nСамый длинный вектор")
print("Координаты:", z)
print("Длина:", maxdlina)

Исходное:
[[0.79949029 0.52844912 0.09605104]
 [0.62762036 0.71555478 0.05464957]
 [0.19252467 0.82999174 0.48965725]
 [0.59223141 0.90009813 0.69237599]
 [0.49224627 0.0118489  0.27770203]
 [0.9565606  0.41146194 0.1072319 ]
 [0.61990905 0.55715837 0.21299232]
 [0.80871328 0.01769079 0.12381082]
 [0.4676192  0.25211588 0.9853696 ]]

Длины векторов:
[0.96315575 0.95336905 0.98270863 1.28074166 0.56530099 1.04680839
 0.8602781  0.81832711 1.11945673]

Самый длинный вектор
Координаты: [0.59223141 0.90009813 0.69237599]
Длина: 0.6694597476936529
