In [ ]:
[1]
import numpy as np
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
[2]
import numpy as np
diagonal = np.arange(1, 5)
matrix = np.diag(diagonal, 1)
print(matrix)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
[3]
a = np.array([1, 6, 8, 5, 8, 4, 8])
mask = (a > 3) & (a < 8)
a[mask] = -a[mask]
print(a)


[ 1 -6  8 -5  8 -4  8]


In [ ]:
[6]

a = np.array([1, 2, 2, 2, 3, 3, 3, 3, 3])
maxx = np.bincount(a)
val = np.argmax(maxx)
print(val)


3


In [ ]:
[4]

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) * 4 - 3)

b[::4] = a

print(b)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
[5]

import numpy as np

a = np.array([[1, 2, 3], [0, 0, 0], [9, 3, 5]])
a[0], a[2] = a[2], a[0].copy()

print(a)


[[9 3 5]
 [0 0 0]
 [1 2 3]]


In [ ]:
[8]

import numpy as np

matrix = np.random.rand(10, 10)
n = int(input())
a = np.sort(matrix.flatten())[-n:]
print(a)

7
[0.8907192  0.92002137 0.93305795 0.93786937 0.94004996 0.98126212
 0.98954935]


In [6]:
[9]

matrix = np.array([[1, 2, 3],
                   [2, 2, 3],
                   [4, 3, 6],
                   [2, 2, 2],
                   [7, 7, 7],
                   [2, 2, 3],
                   [10, 11, 12],
                   [2, 2, 3],
                   [13, 14, 15],
                   [2, 2, 2]])
a = []
for i in matrix:
   if len(set(i)) > 1:
    a.append(i)

for b in a:
    print(b)

[1 2 3]
[2 2 3]
[4 3 6]
[2 2 3]
[10 11 12]
[2 2 3]
[13 14 15]


In [7]:
[10]

import numpy as np

A = np.array([2.3, -4.8, 0.5, -1.2, 3.0, -0.7])
Z = np.where(A > 0, np.ceil(A), np.floor(A))
print(Z)

[ 3. -5.  1. -2.  3. -1.]


In [8]:
[11]

import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
Z = np.intersect1d(A, B)
print(Z)


[3 4 5]


In [9]:
[13]

import numpy as np

matrix = np.random.random((5, 3))
vector_lengths = np.linalg.norm(matrix, axis=1)
max_length_index = np.argmax(vector_lengths)
max_length_vector_coordinates = matrix[max_length_index]
max_length = vector_lengths[max_length_index]
print("Исходная матрица:")
print(matrix)
print("\nДлины векторов:")
print(vector_lengths)
print("\nСамый длинный вектор (его координаты и длина):")
print("Координаты:", max_length_vector_coordinates)
print("Длина:", max_length)


Исходная матрица:
[[0.76913729 0.34084571 0.41959894]
 [0.05002728 0.74905729 0.99116188]
 [0.13349801 0.89300083 0.18424782]
 [0.74350437 0.90166641 0.898394  ]
 [0.35385216 0.72214391 0.50900623]]

Длины векторов:
[0.94011235 1.24337904 0.92153104 1.47408034 0.95173028]

Самый длинный вектор (его координаты и длина):
Координаты: [0.74350437 0.90166641 0.898394  ]
Длина: 1.4740803443349428


In [10]:
[7]

import numpy as np

array_16x16 = np.random.randint(1, 10, size=(16, 16))
array_4x4_blocks = array_16x16.reshape(4, 4, 4, 4)
block_sums = np.sum(array_4x4_blocks, axis=(2, 3))
print("Исходный массив 16x16:")
print(array_16x16)
print("\nСуммы по блокам 4x4:")
print(block_sums)


Исходный массив 16x16:
[[6 1 9 4 4 3 9 1 8 6 8 4 4 3 6 9]
 [1 2 5 3 7 6 9 5 1 1 9 9 2 2 9 3]
 [7 5 1 1 7 9 1 3 7 3 2 2 9 8 1 1]
 [2 6 6 4 5 5 1 7 6 4 9 4 8 5 1 3]
 [9 4 2 1 3 8 6 7 3 2 7 7 8 6 6 1]
 [1 2 8 3 5 4 8 2 9 3 5 7 9 6 6 4]
 [8 8 4 8 7 9 1 1 9 5 3 9 9 6 3 6]
 [1 3 4 4 7 1 1 9 8 5 5 3 6 3 9 7]
 [6 2 8 6 8 1 9 7 9 5 4 7 4 9 1 1]
 [2 8 2 3 3 5 9 8 1 2 3 7 9 7 9 3]
 [4 1 3 9 2 5 8 3 7 3 6 8 6 4 2 8]
 [2 9 5 5 8 7 6 2 9 9 4 3 7 2 9 5]
 [1 7 7 2 2 7 8 8 4 1 6 9 4 5 3 9]
 [3 2 4 8 2 3 9 7 3 3 9 1 5 3 8 6]
 [3 2 4 2 4 8 5 4 3 3 5 9 1 8 5 7]
 [7 4 7 6 1 6 3 4 3 3 7 5 5 4 2 5]]

Суммы по блокам 4x4:
[[85 74 67 76]
 [80 82 96 76]
 [87 81 79 92]
 [83 76 73 72]]


In [ ]:
[12]

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
maxx = 0
for i in range (len(x) - 1):
    if x[i] == 0 and maxx < x[i + 1]:
        maxx = x[i + 1]
print(maxx)


5
