In [2]:
#Task 1
import numpy as np
A = np.ones((10,10))
A[1:-1,1:-1] = 0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
#Task 2
B = np.diag([1,2,3,4],1)
B

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [62]:
#Task 3
C = np.random.randint(1,15,size = (1,15))
print(C)
C[(C > 3) & (C <= 8)] *= -1
C

[[11  7 10  3 11  1  9  5  2  6 10  2 10  6 13]]


array([[11, -7, 10,  3, 11,  1,  9, -5,  2, -6, 10,  2, 10, -6, 13]])

In [8]:
#Task 4
D = np.array([1,2,3,4,5])
E = np.zeros(len(D) * 4 - 3)
E[::4] = D
E

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

In [63]:
#Task 5
F = np.array([[1,2,3], [0,0,0], [9,3,5]])
F[1],F[2] = F[2],F[1].copy()
F

array([[1, 2, 3],
       [9, 3, 5],
       [0, 0, 0]])

In [113]:
#Task 6
G = np.array([1,2,3,4,5,6,7,8,9,0,9,8,7,6,4,23,55,2,1,3,5,6,7,87,53,2,1,3,5,6,2,2,1,1,2,3,1,5,1])
H = np.bincount(G)
print(np.argmax(H))

1


In [38]:
#Task 7
I = np.random.randint(1,100,size = (16,16))
#I #чтобы увидеть исходный массив
J = I.reshape(4,4,4,4)
sum = np.sum(J,axis = (2,3))
sum

ValueError: ignored

In [55]:
#Task 8
K = np.random.randint(1,100,size = (7,7))
print(K)
L = K.flatten()
L.sort()
n = int(input())
L[-n:]


[[73 98 84 79 10 54 70]
 [15 85 79 48 49 49 31]
 [74 48 45  1 17  9 39]
 [65 67 34  8 11  2 67]
 [61 11  8 68 58 84 91]
 [89 23 29  6 96 31 42]
 [31 55 22 93 23 90 45]]
5


array([90, 91, 93, 96, 98])

In [80]:
#Task 9
M = np.random.randint(1,5,size = (10,3))
print(M)
print("    ")
N = []
for i in (M):
  if len(set(i)) != 1:
    N.append(i)
for j in N:
  print(j)

[[2 4 3]
 [1 2 2]
 [4 3 1]
 [4 3 2]
 [4 2 3]
 [3 1 3]
 [1 1 4]
 [3 2 2]
 [3 1 1]
 [4 2 4]]
    
[2 4 3]
[1 2 2]
[4 3 1]
[4 3 2]
[4 2 3]
[3 1 3]
[1 1 4]
[3 2 2]
[3 1 1]
[4 2 4]


In [102]:
#Task 10
O = np.random.uniform(-100,100, (1,20))
print(O)

P = np.where(O > 0, np.ceil(O),np.floor(O))
P

[[ 71.00772638  63.82325563  96.6439379   -5.99476975 -89.78414421
  -42.82616309  64.74033049  20.56172513  -1.1246468   34.75420655
  -92.60215425  -4.97571851 -13.61060256 -82.18014592  32.39272277
  -48.38252612 -32.83997241 -72.9866142   64.59066432 -41.22636473]]


array([[ 72.,  64.,  97.,  -6., -90., -43.,  65.,  21.,  -2.,  35., -93.,
         -5., -14., -83.,  33., -49., -33., -73.,  65., -42.]])

In [106]:
#Task 11
R = np.random.randint(1,6,size = (1,10))
print(R)
S = np.random.randint(1,6,size = (1,10))
print(S)
T = intersect1d(R,S)
T

[[2 2 4 5 2 2 1 4 3 5]]
[[1 5 4 3 5 3 3 4 3 4]]


array([1, 3, 4, 5])

In [111]:
#Task 12
U = np.array((0,1,2,4,0,0,7,9,0,5,0,1,0,5,6,8,3,24,0,77))
max = 0
for i in range(len(U)-1):
  if U[i] == 0 and U[i+1] > max:
    max = U[i+1]
max

77