In [11]:
#4
import numpy as np
l = np.zeros((5, 4))
vsp = np.array([1, 2, 3, 4, 5])
l[:, 0] = vsp
print(l.reshape(1,20)[0, :17])


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [16]:
#5
import numpy as np
l = np.array([[1,2,3], [0,0,0], [9,3,5]])
l[[0,1]] = l[[1, 0]]
print(l)

[[0 0 0]
 [1 2 3]
 [9 3 5]]


In [33]:
#8
import numpy as np


matrix = np.random.rand(10, 10)


n = int(input(">>>"))


nend = np.sort(matrix.flatten())[-n:]


print(nend)


>>>5
[0.95815742 0.96995165 0.97398504 0.98476965 0.99112207]
>>>6
[0.9789535  0.98133778 0.98928612 0.98999538 0.99346377 0.99695476]


In [39]:
#9
import numpy as np


matrix = np.array([[1, 2, 3],
                   [2, 2, 3],
                   [4, 3, 6],
                   [2, 2, 2],
                   [7, 7, 7],
                   [2, 2, 3],
                   [10, 11, 12],
                   [2, 2, 3],
                   [13, 14, 15],
                   [2, 2, 2]])

# Найти строки с неравными значениями
unrows = []
for i in matrix:
   if len(set(i)) > 1:
    unrows.append(i)

for row in unrows:
    print(row)


Строки с неравными значениями:
[1 2 3]
[2 2 3]
[4 3 6]
[2 2 3]
[10 11 12]
[2 2 3]
[13 14 15]


In [62]:
#10
import numpy as np

A = np.random.rand(10)
Z = np.where(A > 0, np.ceil(A), np.floor(A))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
#11
import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

Z = np.intersect1d(A, B)

print(Z)

Пересечение векторов A и B: [3 4 5]


In [19]:
#12
arr = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max = 0
for i in range (len(arr) - 1):
   if max < arr[i + 1] and arr[i] == 0:
     max = arr[i + 1]
print(max)

5


In [52]:
#13
import numpy as np

matrix = np.random.rand(5, 3)

vector_lengths = np.linalg.norm(matrix,axis = 1)

max_length_index = np.argmax(vector_lengths)

max_length_vector = matrix[max_length_index]

print(matrix)
print(vector_lengths)
print( max_length_vector)
print(vector_lengths[max_length_index])

[[0.67356902 0.7489477  0.0880519 ]
 [0.12932612 0.27579019 0.82426521]
 [0.76417076 0.43951085 0.46518808]
 [0.41126125 0.2313444  0.44001689]
 [0.61674405 0.13096445 0.74878219]]
[1.01112364 0.87874832 0.99675809 0.64519059 0.97887674]
[0.67356902 0.7489477  0.0880519 ]
1.0111236434645914
