Numpy

задача 1

In [ ]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


задача 2

In [ ]:
import numpy as np
diagonal = np.arange(1, 5)
matrix = np.diag(diagonal, 1)
print(matrix)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


задача 3

In [ ]:
a = np.array([1, 6, 8, 5, 8, 4, 8])
mask = (a > 3) & (a < 8)
a[mask] = -a[mask]
print(a)



[ 1 -6  8 -5  8 -4  8]


задача 4

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) * 4 - 3)

b[::4] = a

print(b)



[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


задача 5

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [0, 0, 0], [9, 3, 5]])
a[0], a[2] = a[2], a[0].copy()

print(a)


[[9 3 5]
 [0 0 0]
 [1 2 3]]


задача 6

In [ ]:
a = np.array([1, 2, 2, 2, 3, 3, 3, 3, 3])
maxx = np.bincount(a)
val = np.argmax(maxx)
print(val)

3


задача 8

In [ ]:
import numpy as np

matrix = np.random.rand(10, 10)
n = int(input())
a = np.sort(matrix.flatten())[-n:]
print(a)

6
[0.97637891 0.98624903 0.98828523 0.99614405 0.99707032 0.99740266]


задача 10

In [ ]:
import numpy as np

A = np.array([2.3, -4.8, 0.5, -1.2, 3.0, -0.7])
Z = np.where(A > 0, np.ceil(A), np.floor(A))
print(Z)

[ 3. -5.  1. -2.  3. -1.]


задача 11

In [ ]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
Z = np.intersect1d(A, B)
print(Z)


[3 4 5]


задача 12

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
ma = 0
for i in range (len(x) - 1):
    if x[i] == 0 and ma < x[i + 1]:
        ma = x[i + 1]
print(ma)

5
